### ISSUE TITLE
Documentation on Status API is missing an enum entry for `indicator = maintenance`

### ISSUE THREAD

**Issue by wimax-grapl** [cloudsmith-io/cloudsmith-api#25]
(Warning: I suspect this is the wrong repository for this issue report)

Currently if I hit api/v2/status.json, I get
```
curl --silent 'https://status.cloudsmith.io/api/v2/status.json' | jq
{
  "page": {
    "id": "yt0blqw1vlv7",
    "name": "Cloudsmith",
    "url": "https://status.cloudsmith.io",
    "time_zone": "Etc/UTC",
    "updated_at": "2022-01-08T15:49:00.027Z"
  },
  "status": {
    "indicator": "maintenance",
    "description": "Service Under Maintenance"
  }
}
```

If I read the documentation at
https://status.cloudsmith.io/api/v2
it says
```
This endpoint includes an indicator - one of none, minor, major, or critical
```

`maintenance` is not mentioned.

**Comment by jackgibson1** [comment]
Hey @wimax-grapl, thanks for opening an issue and apologies it's taken us until now to get back to you. 

That is frustrating. Unfortunately, however, the API that you're using there is out of our control. A separate [vendor and service](https://status.atlassian.com/api) hosts this particular status page (and API). The engineering team has discussed potentially utilizing another service though, so please keep an eye out!
