### ISSUE TITLE
[API]::[Null Response]Get the details for the specific organization 

### ISSUE THREAD

**Issue by srikanth2302** [cloudsmith-io/cloudsmith-api#53]
We are trying to fetch specific organization details via API: https://api.cloudsmith.io/v1/orgs/{org}. It is resulting in null response as below!!

{
  "name": ""
}

Request to please have a look at it.

**Comment by ralph-mcteggart** [comment]
Thanks @srikanth2302, we're in the process of fixing this!

**Comment by ralph-mcteggart** [comment]
Fixed now @srikanth2302
